version: '3.8'

services:
  game_db:
    image: postgres:17
    container_name: postgres_game_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d game_db"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
    driver: local
