 public class MockResponses
 {
        public static string GameSessionResponse = @"
        {
          ""content"": [
            {
              ""id"": 1,
              ""name"": ""Session 1"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""WAITING"",
              ""startTime"": ""2023-10-01T10:00:00"",
              ""endTime"": ""2023-10-01T11:00:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 1\""}"",
              ""createdAt"": ""2023-09-30T09:00:00"",
              ""updatedAt"": ""2023-09-30T09:10:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 1,
              ""name"": ""Session 2"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""WAITING"",
              ""startTime"": ""2023-10-01T10:00:00"",
              ""endTime"": ""2023-10-01T11:00:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 1\""}"",
              ""createdAt"": ""2023-09-30T09:00:00"",
              ""updatedAt"": ""2023-09-30T09:10:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 1,
              ""name"": ""Session 3"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""WAITING"",
              ""startTime"": ""2023-10-01T10:00:00"",
              ""endTime"": ""2023-10-01T11:00:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 1\""}"",
              ""createdAt"": ""2023-09-30T09:00:00"",
              ""updatedAt"": ""2023-09-30T09:10:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 1,
              ""name"": ""Session 4"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""WAITING"",
              ""startTime"": ""2023-10-01T10:00:00"",
              ""endTime"": ""2023-10-01T11:00:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 1\""}"",
              ""createdAt"": ""2023-09-30T09:00:00"",
              ""updatedAt"": ""2023-09-30T09:10:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 2,
              ""name"": ""Session 5"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""WAITING"",
              ""startTime"": ""2023-10-01T10:05:00"",
              ""endTime"": ""2023-10-01T11:05:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 2\""}"",
              ""createdAt"": ""2023-09-30T09:05:00"",
              ""updatedAt"": ""2023-09-30T09:15:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 3,
              ""name"": ""Session 6"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""WAITING"",
              ""startTime"": ""2023-10-01T10:10:00"",
              ""endTime"": ""2023-10-01T11:10:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 3\""}"",
              ""createdAt"": ""2023-09-30T09:10:00"",
              ""updatedAt"": ""2023-09-30T09:20:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 4,
              ""name"": ""Session 7"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""WAITING"",
              ""startTime"": ""2023-10-01T10:15:00"",
              ""endTime"": ""2023-10-01T11:15:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 4\""}"",
              ""createdAt"": ""2023-09-30T09:15:00"",
              ""updatedAt"": ""2023-09-30T09:25:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 5,
              ""name"": ""Session 8"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""IN_PROGRESS"",
              ""startTime"": ""2023-10-01T10:20:00"",
              ""endTime"": ""2023-10-01T11:20:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 5\""}"",
              ""createdAt"": ""2023-09-30T09:20:00"",
              ""updatedAt"": ""2023-09-30T09:30:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 5,
              ""name"": ""Session 9"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""IN_PROGRESS"",
              ""startTime"": ""2023-10-01T10:20:00"",
              ""endTime"": ""2023-10-01T11:20:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 5\""}"",
              ""createdAt"": ""2023-09-30T09:20:00"",
              ""updatedAt"": ""2023-09-30T09:30:00"",
              ""players"": [],
              ""events"": []
            },
            {
              ""id"": 5,
              ""name"": ""Session 10"",
              ""password"": ""secret"",
              ""maxPlayers"": 10,
              ""status"": ""IN_PROGRESS"",
              ""startTime"": ""2023-10-01T10:20:00"",
              ""endTime"": ""2023-10-01T11:20:00"",
              ""winningTeam"": null,
              ""gameSettings"": ""{\""difficulty\"":\""medium\""}"",
              ""summary"": ""{\""description\"":\""Mock session 5\""}"",
              ""createdAt"": ""2023-09-30T09:20:00"",
              ""updatedAt"": ""2023-09-30T09:30:00"",
              ""players"": [],
              ""events"": []
            }
          ],
          ""last"": true
        }";
        
 }
